'use client'

import { CheerioWebBaseLoader } from 'langchain/document_loaders/web/cheerio';
import { HtmlToTextTransformer } from 'langchain/document_transformers/html_to_text';
import { OpenAIEmbeddings } from 'langchain/embeddings/openai';
import { OpenAI } from 'langchain/llms/openai';
import { PromptTemplate } from 'langchain/prompts';
import { RunnableSequence } from 'langchain/runnables';
import { StringOutputParser } from 'langchain/schema/output_parser';
import { RecursiveCharacterTextSplitter } from 'langchain/text_splitter';
import { formatDocumentsAsString } from 'langchain/util/document';
import { FaissStore } from 'langchain/vectorstores/faiss';
import { useState } from 'react';

const model = new OpenAI({
  openAIApiKey: process.env.NEXT_PUBLIC_OPEN_AI_KEY,
});

const generateDescriptionBasedOnUrl = (url: string) => {
  // const loader = new CheerioWebBaseLoader(url);
  // const docs = await loader.load();
  // const splitter = RecursiveCharacterTextSplitter.fromLanguage("html");
  // const transformer = new HtmlToTextTransformer();
  // const sequence = splitter.pipe(transformer);
  // const newDocuments = await sequence.invoke(docs);
  // const vectorStore = await FaissStore.fromDocuments(
  //   newDocuments,
  //   new OpenAIEmbeddings({ openAIApiKey: process.env.NEXT_PUBLIC_OPEN_AI_KEY })
  // );
  // const retriever = vectorStore.asRetriever();

  // const chain = RunnableSequence.from([
  //   { context: retriever.pipe(formatDocumentsAsString) },
  //   promptTemplate,
  //   model,
  //   new StringOutputParser(),
  // ])
  // const llmResponse = await chain.invoke(url);
  return 'Not implemented yet';
}

export default function Home() {
  const [url, setUrl] = useState('');
  const [answer, setAnswer] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleChange = async (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setUrl(event.target.value);
  };

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setIsLoading(true);
    const llmResponse = generateDescriptionBasedOnUrl(url);
    setAnswer(llmResponse);
    setIsLoading(false);
  };

  return (
    <main className="flex w-4/5 bg-gray-900 flex-col p-7 pt-14">
      <h2 className='text-xl font-bold mb-5'>Get a description of a e-commerce page based on the copied text of the page</h2>
      <p className='mb-10 max-w-2xl'>Input a copied text of a entire page to generate a detailed and captivating page description for an e-commerce website, showcasing the unique features and benefits of each product, enticing potential customers to make a purchase and enhancing the overall shopping experience.</p>
      <form className='flex flex-col max-w-2xl border-gray-800 border p-7' onSubmit={handleSubmit}>
        <label className='mb-3.5'>Add list of products</label>
        <textarea className='w-full rounded bg-gray-600 h-40 p-3.5' value={url} onChange={handleChange} />
        <div className='flex items-end w-full flex-col'>
          <button className='bg-teal-500 w-auto mt-4 p-2 px-4 rounded disabled:opacity-10' disabled={isLoading} type="submit">Submit</button>
        </div>
      </form>
      {!answer ? null : (
        <div className='max-w-2xl border-gray-800 border p-7 mt-3.5'>
          <h3 className='text-lg font-bold mb-2.5'>Description generated by AI:</h3>
          {answer}
        </div>
      )}
    </main>
  );
}
